# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name TEMULATOR_object
#' @title A TEMULATER simulation
#' @description Type the name of the class to see its methods
#' @field print Print the object
#' @field print_cell_types Print contained cell types
#' @field run Start or restart the simulation \itemize{
#' \item Parameter: verbose - bool, Flag indicating if progress should be printed.
#' \item Returns: bool, Indicating success.
#' }
#' @field sample Sample mutations from the population \itemize{
#' \item Parameter: min_vaf - double, Minimum VAF reported.
#' \item Parameter: purity - double, Assumed purity of the tumour.
#' \item Parameter: depth - double, Sequencing depth.
#' \item Parameter: depth_model - int,  Distribution of the sequencing depth (1: poisson, 2: overdispersed beta binomial (default), 3: fixed).
#' \item Returns: data.frame containing mutation information.
#' }
NULL

