# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SimulateTumor <- function(birthrates, deathrates, mutation_rates, clone_start_times, fathers, simulation_end_time, seed, number_clonal_mutations, purity, min_vaf, depth, depth_model, verbose) {
    .Call(`_TEMULATOR_SimulateTumor`, birthrates, deathrates, mutation_rates, clone_start_times, fathers, simulation_end_time, seed, number_clonal_mutations, purity, min_vaf, depth, depth_model, verbose)
}

